### PR TITLE
move core interfaces and use the new core interfaces

### PR DESCRIPTION
**Pull request by PWesterdale**
:guitar:

### CODE REVIEW

**Comment by PWesterdale** [comment]
solves #3 :+1:

**Comment by PWesterdale** [comment]
Passes Tests :boom:

**Comment by steadweb** [comment]
There's an interface that defines `table()` which is used across my mappers. Has this been defined elsewhere? It's a customer specific interface.

**Comment by steadweb** [comment]
Tests also need to be created for Repo and Mapper (that's a job for me)

**Comment by PWesterdale** [comment]
I haz added to milestone :)

**Comment by PWesterdale** [comment]
retest this please

**Comment by steadweb** [comment]
I didn't close this...

**Pull request closed without merging**
